services:
  redis:
    image: redis
  forex-api:
    build:
      context: .
      dockerfile: dockerfile
      target: base
    volumes:
      - ./src:/app/src
      - ./nodemon.json:/app/nodemon.json
    container_name: forex-api
    expose:
     - 3000
    ports:
      - 3000:3000
    environment:
      REDIS_HOST: redis
    command: npm run dev
